##
# @description Action to automate release processes using semantic-release
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
##

##
# @note Define action general information
##
name       : 'Semantic Releasify'
description: 'A GitHub Action for automated releases, changelogs, and package publishing with semantic-release'
author     : 'C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)'

##
# @note Define branding icon
##
branding:
  icon : box
  color: black

##
# @note Define inputs
##
inputs:
  ##
  # @note Branch
  # @link https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches
  ##
  branch:
    description: 'The branch on which release should happen'
    required   : false
    default    : ${{ github.ref_name }}

  ##
  # @note Tag format
  # @link https://semantic-release.gitbook.io/semantic-release/usage/configuration#tagformat
  ##
  tag-format:
    description: 'The Git tag format used by semantic-release to identify releases'
    required   : false
    default    : 'v${version}'

  ##
  # @note Docker registry
  # @note If `default` is an empty string, it defaults to Docker Hub
  # @link https://github.com/esatterwhite/semantic-release-docker?tab=readme-ov-file#options
  ##
  docker-registry:
    description: 'The hostname and port used by the the registry'
    required   : false
    default    : ''

  ##
  # @note Docker project
  # @note If `default` is an empty string, it defaults to the `name` defined
  #       at `package.json`
  # @link https://github.com/esatterwhite/semantic-release-docker?tab=readme-ov-file#options
  ##
  docker-project:
    description: 'The project or repository name to publish the image to'
    required   : false
    default    : ''

  ##
  # @note Docker image
  # @link https://github.com/esatterwhite/semantic-release-docker?tab=readme-ov-file#options
  ##
  docker-image:
    description: 'The name of the image to release'
    required: false
    default: 'app'

  ##
  # @note File used to build the image
  # @link https://github.com/esatterwhite/semantic-release-docker?tab=readme-ov-file#options
  ##
  docker-file:
    description: 'Path to file used to build the image'
    required: false
    default: 'Dockerfile'

  ##
  # @note Docker args
  # @link https://github.com/esatterwhite/semantic-release-docker?tab=readme-ov-file#options
  ##
  docker-args:
    description: 'An object of arguments to use for the image build'
    required: false
    default: '{}'

##
# @note Define action entry point
##
runs:
  using: node20
  main : dist/index.js
